name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
