networks:
  app-tier:
    driver: bridge
services:
  app:
    environment:
      - UID=${UID}
      - COELACANTH_REMOTE_CLIENT_AUTHORIZATION=${COELACANTH_REMOTE_CLIENT_AUTHORIZATION:-}
      - COELACANTH_REMOTE_CLIENT_USER_AGENT=${COELACANTH_REMOTE_CLIENT_USER_AGENT:-}
      - COELACANTH_SCREENSHOT_ONE_API_KEY=${COELACANTH_SCREENSHOT_ONE_API_KEY:-}
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
    working_dir: /app
    command: bash
    networks:
      - app-tier
  chrome:
    image: browserless/chrome:latest
    networks:
      - app-tier
