development: &development
  client: "ferrum" # Options: "ferrum", "screenshot_one", "gotenberg"
  remote_client:
    ws_url: "ws://chrome:3000/chrome"
    timeout: 10 # seconds
    wait_for_idle_timeout: 5 # seconds to wait before giving up on network idle
    headers:
<% if (auth = ENV["COELACANTH_REMOTE_CLIENT_AUTHORIZATION"]).to_s.strip != "" %>
      Authorization: "<%= auth %>"
<% end %>
      User-Agent: "<%= ENV.fetch("COELACANTH_REMOTE_CLIENT_USER_AGENT", "Coelacanth Chrome Extension") %>"
  screenshot_one:
    key: "<%= ENV.fetch("COELACANTH_SCREENSHOT_ONE_API_KEY", "your_screenshot_one_api_key_here") %>"
  gotenberg:
    url: "<%= ENV.fetch("COELACANTH_GOTENBERG_URL", "http://gotenberg:3000") %>"
    open_timeout: 5
    read_timeout: 30
    wait_delay: "<%= ENV.fetch("COELACANTH_GOTENBERG_WAIT_DELAY", "") %>"
    user_agent: "<%= ENV.fetch("COELACANTH_GOTENBERG_USER_AGENT", "") %>"
    extra_http_headers:
  youtube:
    api_key: "<%= ENV.fetch("COELACANTH_YOUTUBE_API_KEY", "") %>"
  morphology:
    # Example configuration:
    # latin_joiners:
    #   - "'"
    #   - "-"
    # japanese_hiragana_suffixes:
    #   - "さん"
    #   - "ちゃん"
    # japanese_category_breaks:
    #   - "kanji_to_katakana"
    #   - "katakana_to_kanji"
    latin_joiners:
      - ","
    japanese_hiragana_suffixes:
      - "ら"
      - "の"
      - "え"
    japanese_category_breaks:
      - "katakana_to_kanji"
test:
  <<: *development
production:
  <<: *development
