development: &development
  client: "ferrum" # Options: "ferrum", "screenshot_one"
  remote_client:
    ws_url: "ws://chrome:3000/chrome"
    timeout: 10 # seconds
    wait_for_idle_timeout: 5 # seconds to wait before giving up on network idle
    headers:
<% if (auth = ENV["COELACANTH_REMOTE_CLIENT_AUTHORIZATION"]).to_s.strip != "" %>
      Authorization: "<%= auth %>"
<% end %>
      User-Agent: "<%= ENV.fetch("COELACANTH_REMOTE_CLIENT_USER_AGENT", "Coelacanth Chrome Extension") %>"
  screenshot_one:
    key: "<%= ENV.fetch("COELACANTH_SCREENSHOT_ONE_API_KEY", "your_screenshot_one_api_key_here") %>"
test:
  <<: *development
production:
  <<: *development
