name: Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version
        id: version
        run: |
          version=$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" lib/coelacanth/version.rb | head -n 1)
          echo "version=$version" >> $GITHUB_ENV
          echo "Version is $version"

      - name: Determine fromTag
        id: from_tag
        run: |
          tags=($(gh release list --exclude-drafts --limit 5 | cut -f1))
          current_tag="v$version"
          if [ "${tags[0]}" = "$current_tag" ]; then
            echo "Same as latest tag, using previous tag: ${tags[1]}"
            echo "from_tag=${tags[1]}" >> $GITHUB_ENV
          else
            echo "New tag detected, using latest: ${tags[0]}"
            echo "from_tag=${tags[0]}" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ env.from_tag }}
          toTag: v${{ env.version }}
          excludeTypes: ""
          includeInvalidCommits: false

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: true
          makeLatest: true
          name: v${{ env.version }}
          tag: v${{ env.version }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
