name: Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version
        id: version
        run: |
          version=$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" lib/coelacanth/version.rb | head -n 1)
          echo "version=v$version" >> $GITHUB_ENV
          echo "Version is v$version"

      - name: Determine tag or HEAD
        id: to_ref
        run: |
          if gh release view "$version" --json tagName > /dev/null 2>&1; then
            echo "to_ref=$version" >> $GITHUB_ENV
            echo "Using tag $version"
          else
            echo "to_ref=HEAD" >> $GITHUB_ENV
            echo "Tag $version not found. Using HEAD as to_ref."
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get previous release tag
        run: |
          latest_release_tag=$(gh release list --exclude-drafts --limit 1 | cut -f1)
          echo "latest_release_tag=$latest_release_tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ env.latest_release_tag }}
          toTag: ${{ env.to_ref }}
          excludeTypes: ""
          includeInvalidCommits: false

      - name: Create Draft Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: true
          makeLatest: true
          name: ${{ env.version }}
          tag: ${{ env.version }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
