name: Ruby Gem

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.3

    - name: Extract version
      id: version
      run: |
        version=$(echo "${GITHUB_REF#refs/tags/}")
        echo "version=$version" >> $GITHUB_ENV

    - name: Generate CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.version }}
        writeToFile: true
        changelogFilePath: CHANGELOG.md
        includeRefIssues: true
        useGitmojis: true

    - name: Commit updated CHANGELOG.md
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add CHANGELOG.md
        git commit -m "docs: update CHANGELOG for ${{ env.version }}" || echo "No changes to commit"
        git push origin HEAD:main
      continue-on-error: true

    - name: Update GitHub Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: ${{ env.version }}
        name: ${{ env.version }}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_AUTH_TOKEN }}"
